# Generated by Django 5.2.6 on 2025-10-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['-unit_amount']},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-created_at'], 'permissions': [('basic_access', 'Can access basic features'), ('pro_access', 'Can access professional features'), ('advance_access', 'Can access advanced features')]},
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='trial_period_days',
        ),
        migrations.AddField(
            model_name='subscriptionprice',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='permission_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('advanced', 'Advanced')], default='basic', max_length=15),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
        ),
    ]
